
SRCS += \
	$(KEYBOARD_DIR)/m65.c \
	$(KEYBOARD_DIR)/m65_actionmap.c \

MCU = STM32F722
TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
SCREEN_ENABLE = yes
MSC_ENABLE = yes
ACTIONMAP_ENABLE = yes
WEBUSB_ENABLE = yes
RGB_EFFECTS_ENABLE = ws2812

LINKER_PATH = $(KEYBOARD_DIR)