
SRCS += \
	$(KEYBOARD_DIR)/m65.c \
	$(KEYBOARD_DIR)/m65_keymap.c \

MCU = STM32F722
TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
SCREEN_ENABLE = yes
MSC_ENABLE = yes
WEBUSB_ENABLE = yes
EECONFIG_FLASH = yes
RGB_LINEAR_ENABLE = yes
#ACTIONMAP_ENABLE = yes

LINKER_PATH = $(KEYBOARD_DIR)
