
MCU = STM32L432
TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
#RGB_LINEAR_ENABLE = yes
EECONFIG_FLASH = yes
VIAL_ENABLE = yes
#HID_OTHER_ENABLE = no
#CDC_ENABLE = yes
#NKRO_AUTO_ENABLE = yes

LINKER_PATH = $(KEYBOARD_DIR)

UF2_ENABLE = yes
UF2_FAMILY = STM32L4

SRCS += $(KEYBOARD_DIR)/des_19.c
SRCS += $(KEYBOARD_DIR)/des_19_gcmap.c
SRCS += $(KEYBOARD_DIR)/ec_matrix.c
