
MCU = GD32E505
TINYUSB_ENABLE = yes
RGB_LINEAR_ENABLE = yes
#RGB_MATRIX_ENABLE = yes
VIAL_ENABLE = yes
EECONFIG_FLASH = yes
NKRO_ENABLE = yes
PORT_SCAN_ENABLE = yes
STATE_SCAN_ENABLE = yes
DEBOUNCE_TYPE = none #asym_eager_defer_pk

#RTOS_ENABLE = yes
UF2_ENABLE = yes
UF2_FAMILY = GD32E5

SRCS += $(KEYBOARD_DIR)/rabbit60.c

LINKER_PATH = $(KEYBOARD_DIR)

NO_DEBUG := 0