
MCU = STM32F405

TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
#MSC_ENABLE = yes
EECONFIG_FLASH = yes
RGB_LINEAR_ENABLE = yes
#DYNAMIC_CONFIGURATION = yes
USE_F405_V2 = yes
UF2_ENABLE = yes
UF2_FAMILY = STM32F4
VIAL_ENABLE = yes
NKRO_ENABLE = yes

LINKER_PATH = $(KEYBOARD_DIR)

SRCS += $(KEYBOARD_DIR)/vita_c.c
#SRCS += $(KEYBOARD_DIR)/display.c
#SRCS += $(MAIN_DIR)/drivers/ssd1357.c
