
#MCU = STM32F411
MCU = STM32G431
TINYUSB_ENABLE = yes
#TINYUSB_USE_HAL = yes
#RGB_LINEAR_ENABLE = yes
EECONFIG_FLASH = yes
VIAL_ENABLE = yes
NKRO_ENABLE = yes
AMK_CUSTOM_MATRIX = yes

LINKER_PATH = $(KEYBOARD_DIR)

UF2_ENABLE = yes
UF2_FAMILY = STM32G4

SRCS += $(KEYBOARD_DIR)/des_60.c
SRCS += $(KEYBOARD_DIR)/ec_matrix.c
