
#MCU = STM32F411
MCU = STM32G431
TINYUSB_ENABLE = yes
#TINYUSB_USE_HAL = yes
#RGB_LINEAR_ENABLE = yes
EECONFIG_FLASH = yes
#MATRIX_EC_ENABLE = yes
VIAL_ENABLE = yes
NKRO_AUTO_ENABLE = yes

LINKER_PATH = $(KEYBOARD_DIR)

UF2_ENABLE = yes
UF2_FAMILY = STM32G4

SRCS += $(KEYBOARD_DIR)/hhkb_des.c
SRCS += $(KEYBOARD_DIR)/hhkb_des_gcmap.c
SRCS += $(KEYBOARD_DIR)/ec_matrix.c

#HID_OTHER_ENABLE = no
#CDC_ENABLE = yes