
MCU = STM32F446
TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
RGB_LINEAR_ENABLE = yes
AMK_CUSTOM_MATRIX = yes
EECONFIG_FLASH = yes
VIAL_ENABLE = yes
MSC_ENABLE = yes
DYNAMIC_CONFIGURATION = yes
NKRO_ENABLE = yes

#DEBOUNCE_TYPE = none

LINKER_PATH = $(KEYBOARD_DIR)

UF2_ENABLE = yes
UF2_FAMILY = STM32F4

SRCS += $(KEYBOARD_DIR)/8xv3_ec.c
SRCS +=	$(KEYBOARD_DIR)/display.c
SRCS +=	$(MAIN_DIR)/drivers/st7735.c
#SRCS +=	$(KEYBOARD_DIR)/apc_matrix.c
SRCS += $(KEYBOARD_DIR)/ec_matrix.c
