/**
 * Copyright 2021 astro. All rights reserved.
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 */

/**
 * @file amk_gpio.h
 * @brief generic pin implementation
 */

#pragma once

#include <stdint.h>

#if defined(NRF52832_XXAA) || defined(NRF52840_XXAA)
    #include "nrf_gpio.h"
    typedef uint32_t pin_t;
    typedef uint32_t port_t;
    #define INVALID_PIN 0xFFFFFFFF

    #define P0_0 NRF_GPIO_PIN_MAP(0,0)
    #define P0_1 NRF_GPIO_PIN_MAP(0,1)
    #define P0_2 NRF_GPIO_PIN_MAP(0,2)
    #define P0_3 NRF_GPIO_PIN_MAP(0,3)
    #define P0_4 NRF_GPIO_PIN_MAP(0,4)
    #define P0_5 NRF_GPIO_PIN_MAP(0,5)
    #define P0_6 NRF_GPIO_PIN_MAP(0,6)
    #define P0_7 NRF_GPIO_PIN_MAP(0,7)
    #define P0_8 NRF_GPIO_PIN_MAP(0,8)
    #define P0_9 NRF_GPIO_PIN_MAP(0,9)
    #define P0_10 NRF_GPIO_PIN_MAP(0,10)
    #define P0_11 NRF_GPIO_PIN_MAP(0,11)
    #define P0_12 NRF_GPIO_PIN_MAP(0,12)
    #define P0_13 NRF_GPIO_PIN_MAP(0,13)
    #define P0_14 NRF_GPIO_PIN_MAP(0,14)
    #define P0_15 NRF_GPIO_PIN_MAP(0,15)
    #define P0_16 NRF_GPIO_PIN_MAP(0,16)
    #define P0_17 NRF_GPIO_PIN_MAP(0,17)
    #define P0_18 NRF_GPIO_PIN_MAP(0,18)
    #define P0_19 NRF_GPIO_PIN_MAP(0,19)
    #define P0_20 NRF_GPIO_PIN_MAP(0,20)
    #define P0_21 NRF_GPIO_PIN_MAP(0,21)
    #define P0_22 NRF_GPIO_PIN_MAP(0,22)
    #define P0_23 NRF_GPIO_PIN_MAP(0,23)
    #define P0_24 NRF_GPIO_PIN_MAP(0,24)
    #define P0_25 NRF_GPIO_PIN_MAP(0,25)
    #define P0_26 NRF_GPIO_PIN_MAP(0,26)
    #define P0_27 NRF_GPIO_PIN_MAP(0,27)
    #define P0_28 NRF_GPIO_PIN_MAP(0,28)
    #define P0_29 NRF_GPIO_PIN_MAP(0,29)
    #define P0_30 NRF_GPIO_PIN_MAP(0,30)
    #define P0_31 NRF_GPIO_PIN_MAP(0,31)

    #define P1_0 NRF_GPIO_PIN_MAP(1,0)
    #define P1_1 NRF_GPIO_PIN_MAP(1,1)
    #define P1_2 NRF_GPIO_PIN_MAP(1,2)
    #define P1_3 NRF_GPIO_PIN_MAP(1,3)
    #define P1_4 NRF_GPIO_PIN_MAP(1,4)
    #define P1_5 NRF_GPIO_PIN_MAP(1,5)
    #define P1_6 NRF_GPIO_PIN_MAP(1,6)
    #define P1_7 NRF_GPIO_PIN_MAP(1,7)
    #define P1_8 NRF_GPIO_PIN_MAP(1,8)
    #define P1_9 NRF_GPIO_PIN_MAP(1,9)
    #define P1_10 NRF_GPIO_PIN_MAP(1,10)
    #define P1_11 NRF_GPIO_PIN_MAP(1,11)
    #define P1_12 NRF_GPIO_PIN_MAP(1,12)
    #define P1_13 NRF_GPIO_PIN_MAP(1,13)
    #define P1_14 NRF_GPIO_PIN_MAP(1,14)
    #define P1_15 NRF_GPIO_PIN_MAP(1,15)
    #define P1_16 NRF_GPIO_PIN_MAP(1,16)
    #define P1_17 NRF_GPIO_PIN_MAP(1,17)
    #define P1_18 NRF_GPIO_PIN_MAP(1,18)
    #define P1_19 NRF_GPIO_PIN_MAP(1,19)
    #define P1_20 NRF_GPIO_PIN_MAP(1,20)
    #define P1_21 NRF_GPIO_PIN_MAP(1,21)
    #define P1_22 NRF_GPIO_PIN_MAP(1,22)
    #define P1_23 NRF_GPIO_PIN_MAP(1,23)
    #define P1_24 NRF_GPIO_PIN_MAP(1,24)
    #define P1_25 NRF_GPIO_PIN_MAP(1,25)
    #define P1_26 NRF_GPIO_PIN_MAP(1,26)
    #define P1_27 NRF_GPIO_PIN_MAP(1,27)
    #define P1_28 NRF_GPIO_PIN_MAP(1,28)
    #define P1_29 NRF_GPIO_PIN_MAP(1,29)
    #define P1_30 NRF_GPIO_PIN_MAP(1,30)
    #define P1_31 NRF_GPIO_PIN_MAP(1,31)

#elif defined(STM32F401xC) || defined(STM32F411xE) || defined(STM32F405xx) || defined(STM32F722xx) || defined(STM32F103xB) || defined(STM32L432xx) || defined(STM32L072xx) || defined(STM32F446xx) || defined(STM32G431xx)

    #include "generic_hal.h"

    #define INVALID_PIN 0xFFFFFFFF
    typedef uint32_t pin_t;
    typedef uint32_t port_t;

    #define PIN_BIT(pin, pos) ((((pin)>>(pos))&1) == 1 ? (pos) : (pin))
    #define PIN_C(x) \
    PIN_BIT(PIN_BIT(PIN_BIT(PIN_BIT(\
    PIN_BIT(PIN_BIT(PIN_BIT(PIN_BIT(\
    PIN_BIT(PIN_BIT(PIN_BIT(PIN_BIT(\
    PIN_BIT(PIN_BIT(PIN_BIT(PIN_BIT((x),\
    0),1),2),3),4),5),6),7),8),9),10),11),12),13),14),15)

    #define PIN_P(x) (1<<(x))

    //#define MAKE_PIN(port, pin) (((uint32_t)(port))|((PIN_C(pin))&0x0F))
    #define MAKE_PIN(port, pin) (((uint32_t)(port))|((pin)&0x0F))
    #define GET_PIN(port_pin) PIN_P(((port_pin)&0x0F))
    #define GET_PORT(port_pin) ((GPIO_TypeDef*)((port_pin)&~0x0F))

    #define A0 MAKE_PIN(GPIOA, 0)
    #define A1 MAKE_PIN(GPIOA, 1)
    #define A2 MAKE_PIN(GPIOA, 2)
    #define A3 MAKE_PIN(GPIOA, 3)
    #define A4 MAKE_PIN(GPIOA, 4)
    #define A5 MAKE_PIN(GPIOA, 5)
    #define A6 MAKE_PIN(GPIOA, 6)
    #define A7 MAKE_PIN(GPIOA, 7)
    #define A8 MAKE_PIN(GPIOA, 8)
    #define A9 MAKE_PIN(GPIOA, 9)
    #define A10 MAKE_PIN(GPIOA, 10)
    #define A11 MAKE_PIN(GPIOA, 11)
    #define A12 MAKE_PIN(GPIOA, 12)
    #define A13 MAKE_PIN(GPIOA, 13)
    #define A14 MAKE_PIN(GPIOA, 14)
    #define A15 MAKE_PIN(GPIOA, 15)

    #define B0 MAKE_PIN(GPIOB, 0)
    #define B1 MAKE_PIN(GPIOB, 1)
    #define B2 MAKE_PIN(GPIOB, 2)
    #define B3 MAKE_PIN(GPIOB, 3)
    #define B4 MAKE_PIN(GPIOB, 4)
    #define B5 MAKE_PIN(GPIOB, 5)
    #define B6 MAKE_PIN(GPIOB, 6)
    #define B7 MAKE_PIN(GPIOB, 7)
    #define B8 MAKE_PIN(GPIOB, 8)
    #define B9 MAKE_PIN(GPIOB, 9)
    #define B10 MAKE_PIN(GPIOB, 10)
    #define B11 MAKE_PIN(GPIOB, 11)
    #define B12 MAKE_PIN(GPIOB, 12)
    #define B13 MAKE_PIN(GPIOB, 13)
    #define B14 MAKE_PIN(GPIOB, 14)
    #define B15 MAKE_PIN(GPIOB, 15)

    #define C0 MAKE_PIN(GPIOC, 0)
    #define C1 MAKE_PIN(GPIOC, 1)
    #define C2 MAKE_PIN(GPIOC, 2)
    #define C3 MAKE_PIN(GPIOC, 3)
    #define C4 MAKE_PIN(GPIOC, 4)
    #define C5 MAKE_PIN(GPIOC, 5)
    #define C6 MAKE_PIN(GPIOC, 6)
    #define C7 MAKE_PIN(GPIOC, 7)
    #define C8 MAKE_PIN(GPIOC, 8)
    #define C9 MAKE_PIN(GPIOC, 9)
    #define C10 MAKE_PIN(GPIOC, 10)
    #define C11 MAKE_PIN(GPIOC, 11)
    #define C12 MAKE_PIN(GPIOC, 12)
    #define C13 MAKE_PIN(GPIOC, 13)
    #define C14 MAKE_PIN(GPIOC, 14)
    #define C15 MAKE_PIN(GPIOC, 15)

    #define D0 MAKE_PIN(GPIOD, 0)
    #define D1 MAKE_PIN(GPIOD, 1)
    #define D2 MAKE_PIN(GPIOD, 2)
    #define D3 MAKE_PIN(GPIOD, 3)
    #define D4 MAKE_PIN(GPIOD, 4)
    #define D5 MAKE_PIN(GPIOD, 5)
    #define D6 MAKE_PIN(GPIOD, 6)
    #define D7 MAKE_PIN(GPIOD, 7)
    #define D8 MAKE_PIN(GPIOD, 8)
    #define D9 MAKE_PIN(GPIOD, 9)
    #define D10 MAKE_PIN(GPIOD, 10)
    #define D11 MAKE_PIN(GPIOD, 11)
    #define D12 MAKE_PIN(GPIOD, 12)
    #define D13 MAKE_PIN(GPIOD, 13)
    #define D14 MAKE_PIN(GPIOD, 14)
    #define D15 MAKE_PIN(GPIOD, 15)
#elif defined(__SAMD21G18A__)
    #include "generic_hal.h"
    typedef uint8_t pin_t;

    #define GPIO_PIN_FUNCTION_A 0
    #define GPIO_PIN_FUNCTION_B 1
    #define GPIO_PIN_FUNCTION_C 2
    #define GPIO_PIN_FUNCTION_D 3
    #define GPIO_PIN_FUNCTION_E 4
    #define GPIO_PIN_FUNCTION_F 5
    #define GPIO_PIN_FUNCTION_G 6
    #define GPIO_PIN_FUNCTION_H 7

    #define A0 GPIO(GPIO_PORTA, 0)
    #define A1 GPIO(GPIO_PORTA, 1)
    #define A2 GPIO(GPIO_PORTA, 2)
    #define A3 GPIO(GPIO_PORTA, 3)
    #define A4 GPIO(GPIO_PORTA, 4)
    #define A5 GPIO(GPIO_PORTA, 5)
    #define A6 GPIO(GPIO_PORTA, 6)
    #define A7 GPIO(GPIO_PORTA, 7)
    #define A8 GPIO(GPIO_PORTA, 8)
    #define A9 GPIO(GPIO_PORTA, 9)
    #define A10 GPIO(GPIO_PORTA, 10)
    #define A11 GPIO(GPIO_PORTA, 11)
    #define A12 GPIO(GPIO_PORTA, 12)
    #define A13 GPIO(GPIO_PORTA, 13)
    #define A14 GPIO(GPIO_PORTA, 14)
    #define A15 GPIO(GPIO_PORTA, 15)
    #define A16 GPIO(GPIO_PORTA, 16)
    #define A17 GPIO(GPIO_PORTA, 17)
    #define A18 GPIO(GPIO_PORTA, 18)
    #define A19 GPIO(GPIO_PORTA, 19)
    #define A20 GPIO(GPIO_PORTA, 20)
    #define A21 GPIO(GPIO_PORTA, 21)
    #define A22 GPIO(GPIO_PORTA, 22)
    #define A23 GPIO(GPIO_PORTA, 23)
    #define A24 GPIO(GPIO_PORTA, 24)
    #define A25 GPIO(GPIO_PORTA, 25)
    #define A26 GPIO(GPIO_PORTA, 26)
    #define A27 GPIO(GPIO_PORTA, 27)
    #define A28 GPIO(GPIO_PORTA, 28)
    #define A29 GPIO(GPIO_PORTA, 29)
    #define A30 GPIO(GPIO_PORTA, 30)
    #define A31 GPIO(GPIO_PORTA, 31)

    #define B0 GPIO(GPIO_PORTB, 0)
    #define B1 GPIO(GPIO_PORTB, 1)
    #define B2 GPIO(GPIO_PORTB, 2)
    #define B3 GPIO(GPIO_PORTB, 3)
    #define B4 GPIO(GPIO_PORTB, 4)
    #define B5 GPIO(GPIO_PORTB, 5)
    #define B6 GPIO(GPIO_PORTB, 6)
    #define B7 GPIO(GPIO_PORTB, 7)
    #define B8 GPIO(GPIO_PORTB, 8)
    #define B9 GPIO(GPIO_PORTB, 9)
    #define B10 GPIO(GPIO_PORTB, 10)
    #define B11 GPIO(GPIO_PORTB, 11)
    #define B12 GPIO(GPIO_PORTB, 12)
    #define B13 GPIO(GPIO_PORTB, 13)
    #define B14 GPIO(GPIO_PORTB, 14)
    #define B15 GPIO(GPIO_PORTB, 15)
    #define B16 GPIO(GPIO_PORTB, 16)
    #define B17 GPIO(GPIO_PORTB, 17)
    #define B18 GPIO(GPIO_PORTB, 18)
    #define B19 GPIO(GPIO_PORTB, 19)
    #define B20 GPIO(GPIO_PORTB, 20)
    #define B21 GPIO(GPIO_PORTB, 21)
    #define B22 GPIO(GPIO_PORTB, 22)
    #define B23 GPIO(GPIO_PORTB, 23)
    #define B24 GPIO(GPIO_PORTB, 24)
    #define B25 GPIO(GPIO_PORTB, 25)
    #define B26 GPIO(GPIO_PORTB, 26)
    #define B27 GPIO(GPIO_PORTB, 27)
    #define B28 GPIO(GPIO_PORTB, 28)
    #define B29 GPIO(GPIO_PORTB, 29)
    #define B30 GPIO(GPIO_PORTB, 30)
    #define B31 GPIO(GPIO_PORTB, 31)
#elif   defined(M484)
    #include "generic_hal.h"
    typedef uint32_t pin_t;
    typedef uint32_t port_t;

    #define PIN_P(x) (1<<(x))
    #define MAKE_PIN(port, pin) ((GPIO_PIN_DATA_BASE+(0x40*(port))) + ((pin)<<2))
    #define GET_PIN(port_pin)   PIN_P((((port_pin)%0x40)>>2))

    #define A0      MAKE_PIN(0,0)
    #define A1      MAKE_PIN(0,1)
    #define A2      MAKE_PIN(0,2)
    #define A3      MAKE_PIN(0,3)
    #define A4      MAKE_PIN(0,4)
    #define A5      MAKE_PIN(0,5)
    #define A6      MAKE_PIN(0,6)
    #define A7      MAKE_PIN(0,7)
    #define A8      MAKE_PIN(0,8)
    #define A9      MAKE_PIN(0,9)
    #define A10     MAKE_PIN(0,10)
    #define A11     MAKE_PIN(0,11)
    #define A12     MAKE_PIN(0,12)
    #define A13     MAKE_PIN(0,13)
    #define A14     MAKE_PIN(0,14)
    #define A15     MAKE_PIN(0,15)
    #define B0      MAKE_PIN(1,0)
    #define B1      MAKE_PIN(1,1)
    #define B2      MAKE_PIN(1,2)
    #define B3      MAKE_PIN(1,3)
    #define B4      MAKE_PIN(1,4)
    #define B5      MAKE_PIN(1,5)
    #define B6      MAKE_PIN(1,6)
    #define B7      MAKE_PIN(1,7)
    #define B8      MAKE_PIN(1,8)
    #define B9      MAKE_PIN(1,9)
    #define B10     MAKE_PIN(1,10)
    #define B11     MAKE_PIN(1,11)
    #define B12     MAKE_PIN(1,12)
    #define B13     MAKE_PIN(1,13)
    #define B14     MAKE_PIN(1,14)
    #define B15     MAKE_PIN(1,15)
    #define C0      MAKE_PIN(2,0)
    #define C1      MAKE_PIN(2,1)
    #define C2      MAKE_PIN(2,2)
    #define C3      MAKE_PIN(2,3)
    #define C4      MAKE_PIN(2,4)
    #define C5      MAKE_PIN(2,5)
    #define C6      MAKE_PIN(2,6)
    #define C7      MAKE_PIN(2,7)
    #define C8      MAKE_PIN(2,8)
    #define C9      MAKE_PIN(2,9)
    #define C10     MAKE_PIN(2,10)
    #define C11     MAKE_PIN(2,11)
    #define C12     MAKE_PIN(2,12)
    #define C13     MAKE_PIN(2,13)
    #define C14     MAKE_PIN(2,14)
    #define C15     MAKE_PIN(2,15)
    #define D0      MAKE_PIN(3,0)
    #define D1      MAKE_PIN(3,1)
    #define D2      MAKE_PIN(3,2)
    #define D3      MAKE_PIN(3,3)
    #define D4      MAKE_PIN(3,4)
    #define D5      MAKE_PIN(3,5)
    #define D6      MAKE_PIN(3,6)
    #define D7      MAKE_PIN(3,7)
    #define D8      MAKE_PIN(3,8)
    #define D9      MAKE_PIN(3,9)
    #define D10     MAKE_PIN(3,10)
    #define D11     MAKE_PIN(3,11)
    #define D12     MAKE_PIN(3,12)
    #define D13     MAKE_PIN(3,13)
    #define D14     MAKE_PIN(3,14)
    #define D15     MAKE_PIN(3,15)
    #define E0      MAKE_PIN(4,0)
    #define E1      MAKE_PIN(4,1)
    #define E2      MAKE_PIN(4,2)
    #define E3      MAKE_PIN(4,3)
    #define E4      MAKE_PIN(4,4)
    #define E5      MAKE_PIN(4,5)
    #define E6      MAKE_PIN(4,6)
    #define E7      MAKE_PIN(4,7)
    #define E8      MAKE_PIN(4,8)
    #define E9      MAKE_PIN(4,9)
    #define E10     MAKE_PIN(4,10)
    #define E11     MAKE_PIN(4,11)
    #define E12     MAKE_PIN(4,12)
    #define E13     MAKE_PIN(4,13)
    #define E14     MAKE_PIN(4,14)
    #define E15     MAKE_PIN(4,15)
    #define F0      MAKE_PIN(5,0)
    #define F1      MAKE_PIN(5,1)
    #define F2      MAKE_PIN(5,2)
    #define F3      MAKE_PIN(5,3)
    #define F4      MAKE_PIN(5,4)
    #define F5      MAKE_PIN(5,5)
    #define F6      MAKE_PIN(5,6)
    #define F7      MAKE_PIN(5,7)
    #define F8      MAKE_PIN(5,8)
    #define F9      MAKE_PIN(5,9)
    #define F10     MAKE_PIN(5,10)
    #define F11     MAKE_PIN(5,11)
    #define F12     MAKE_PIN(5,12)
    #define F13     MAKE_PIN(5,13)
    #define F14     MAKE_PIN(5,14)
    #define F15     MAKE_PIN(5,15)
    #define G0      MAKE_PIN(6,0)
    #define G1      MAKE_PIN(6,1)
    #define G2      MAKE_PIN(6,2)
    #define G3      MAKE_PIN(6,3)
    #define G4      MAKE_PIN(6,4)
    #define G5      MAKE_PIN(6,5)
    #define G6      MAKE_PIN(6,6)
    #define G7      MAKE_PIN(6,7)
    #define G8      MAKE_PIN(6,8)
    #define G9      MAKE_PIN(6,9)
    #define G10     MAKE_PIN(6,10)
    #define G11     MAKE_PIN(6,11)
    #define G12     MAKE_PIN(6,12)
    #define G13     MAKE_PIN(6,13)
    #define G14     MAKE_PIN(6,14)
    #define G15     MAKE_PIN(6,15)
    #define H0      MAKE_PIN(7,0)
    #define H1      MAKE_PIN(7,1)
    #define H2      MAKE_PIN(7,2)
    #define H3      MAKE_PIN(7,3)
    #define H4      MAKE_PIN(7,4)
    #define H5      MAKE_PIN(7,5)
    #define H6      MAKE_PIN(7,6)
    #define H7      MAKE_PIN(7,7)
    #define H8      MAKE_PIN(7,8)
    #define H9      MAKE_PIN(7,9)
    #define H10     MAKE_PIN(7,10)
    #define H11     MAKE_PIN(7,11)
    #define H12     MAKE_PIN(7,12)
    #define H13     MAKE_PIN(7,13)
    #define H14     MAKE_PIN(7,14)
    #define H15     MAKE_PIN(7,15)
    #define I0      MAKE_PIN(8,1)
    #define I1      MAKE_PIN(8,1)
    #define I2      MAKE_PIN(8,2)
    #define I3      MAKE_PIN(8,3)
    #define I4      MAKE_PIN(8,4)
    #define I5      MAKE_PIN(8,5)
    #define I6      MAKE_PIN(8,6)
    #define I7      MAKE_PIN(8,7)
    #define I8      MAKE_PIN(8,8)
    #define I9      MAKE_PIN(8,9)
    #define I10     MAKE_PIN(8,10)
    #define I11     MAKE_PIN(8,11)
    #define I12     MAKE_PIN(8,12)
    #define I13     MAKE_PIN(8,13)
    #define I14     MAKE_PIN(8,14)
    #define I15     MAKE_PIN(8,15)
#elif defined(GD32E10X) || defined(GD32E50X)
    #include "generic_hal.h"

    typedef uint32_t pin_t;
    typedef uint32_t port_t;
    #define PIN_P(x) (1<<(x))
    #define MAKE_PIN(port, pin) (((uint32_t)(port))|((pin)&0x0F))
    #define GET_PIN(port_pin) PIN_P(((port_pin)&0x0F))
    #define GET_PORT(port_pin) ((port_pin)&~0x0F)

    #define PORT_A  GPIOA
    #define PORT_B  GPIOB
    #define PORT_C  GPIOC
    #define PORT_D  GPIOD

    #define A0 MAKE_PIN(GPIOA, 0)
    #define A1 MAKE_PIN(GPIOA, 1)
    #define A2 MAKE_PIN(GPIOA, 2)
    #define A3 MAKE_PIN(GPIOA, 3)
    #define A4 MAKE_PIN(GPIOA, 4)
    #define A5 MAKE_PIN(GPIOA, 5)
    #define A6 MAKE_PIN(GPIOA, 6)
    #define A7 MAKE_PIN(GPIOA, 7)
    #define A8 MAKE_PIN(GPIOA, 8)
    #define A9 MAKE_PIN(GPIOA, 9)
    #define A10 MAKE_PIN(GPIOA, 10)
    #define A11 MAKE_PIN(GPIOA, 11)
    #define A12 MAKE_PIN(GPIOA, 12)
    #define A13 MAKE_PIN(GPIOA, 13)
    #define A14 MAKE_PIN(GPIOA, 14)
    #define A15 MAKE_PIN(GPIOA, 15)

    #define B0 MAKE_PIN(GPIOB, 0)
    #define B1 MAKE_PIN(GPIOB, 1)
    #define B2 MAKE_PIN(GPIOB, 2)
    #define B3 MAKE_PIN(GPIOB, 3)
    #define B4 MAKE_PIN(GPIOB, 4)
    #define B5 MAKE_PIN(GPIOB, 5)
    #define B6 MAKE_PIN(GPIOB, 6)
    #define B7 MAKE_PIN(GPIOB, 7)
    #define B8 MAKE_PIN(GPIOB, 8)
    #define B9 MAKE_PIN(GPIOB, 9)
    #define B10 MAKE_PIN(GPIOB, 10)
    #define B11 MAKE_PIN(GPIOB, 11)
    #define B12 MAKE_PIN(GPIOB, 12)
    #define B13 MAKE_PIN(GPIOB, 13)
    #define B14 MAKE_PIN(GPIOB, 14)
    #define B15 MAKE_PIN(GPIOB, 15)

    #define C0 MAKE_PIN(GPIOC, 0)
    #define C1 MAKE_PIN(GPIOC, 1)
    #define C2 MAKE_PIN(GPIOC, 2)
    #define C3 MAKE_PIN(GPIOC, 3)
    #define C4 MAKE_PIN(GPIOC, 4)
    #define C5 MAKE_PIN(GPIOC, 5)
    #define C6 MAKE_PIN(GPIOC, 6)
    #define C7 MAKE_PIN(GPIOC, 7)
    #define C8 MAKE_PIN(GPIOC, 8)
    #define C9 MAKE_PIN(GPIOC, 9)
    #define C10 MAKE_PIN(GPIOC, 10)
    #define C11 MAKE_PIN(GPIOC, 11)
    #define C12 MAKE_PIN(GPIOC, 12)
    #define C13 MAKE_PIN(GPIOC, 13)
    #define C14 MAKE_PIN(GPIOC, 14)
    #define C15 MAKE_PIN(GPIOC, 15)

    #define D0 MAKE_PIN(GPIOD, 0)
    #define D1 MAKE_PIN(GPIOD, 1)
    #define D2 MAKE_PIN(GPIOD, 2)
    #define D3 MAKE_PIN(GPIOD, 3)
    #define D4 MAKE_PIN(GPIOD, 4)
    #define D5 MAKE_PIN(GPIOD, 5)
    #define D6 MAKE_PIN(GPIOD, 6)
    #define D7 MAKE_PIN(GPIOD, 7)
    #define D8 MAKE_PIN(GPIOD, 8)
    #define D9 MAKE_PIN(GPIOD, 9)
    #define D10 MAKE_PIN(GPIOD, 10)
    #define D11 MAKE_PIN(GPIOD, 11)
    #define D12 MAKE_PIN(GPIOD, 12)
    #define D13 MAKE_PIN(GPIOD, 13)
    #define D14 MAKE_PIN(GPIOD, 14)
    #define D15 MAKE_PIN(GPIOD, 15)
#elif defined(HC32F460xE)
    #include "generic_hal.h"

    #define INVALID_PIN 0xFFFFFFFF
    typedef uint32_t pin_t;
    typedef uint32_t port_t;

    #define MAKE_PIN(port, pin)     ((uint32_t) (((port)<<16)|((pin)&0xFFFF)))
    #define GET_PIN(port_pin)       ((port_pin)&0xFFFF)
    #define GET_PORT(port_pin)      (((port_pin)>>16)&0xFFFF)

    #define  A0 MAKE_PIN(PortA, Pin00)
    #define  A1 MAKE_PIN(PortA, Pin01)
    #define  A2 MAKE_PIN(PortA, Pin02)
    #define  A3 MAKE_PIN(PortA, Pin03)
    #define  A4 MAKE_PIN(PortA, Pin04)
    #define  A5 MAKE_PIN(PortA, Pin05)
    #define  A6 MAKE_PIN(PortA, Pin06)
    #define  A7 MAKE_PIN(PortA, Pin07)
    #define  A8 MAKE_PIN(PortA, Pin08)
    #define  A9 MAKE_PIN(PortA, Pin09)
    #define A10 MAKE_PIN(PortA, Pin10)
    #define A11 MAKE_PIN(PortA, Pin11)
    #define A12 MAKE_PIN(PortA, Pin12)
    #define A13 MAKE_PIN(PortA, Pin13)
    #define A14 MAKE_PIN(PortA, Pin14)
    #define A15 MAKE_PIN(PortA, Pin15)

    #define  B0 MAKE_PIN(PortB, Pin00)
    #define  B1 MAKE_PIN(PortB, Pin01)
    #define  B2 MAKE_PIN(PortB, Pin02)
    #define  B3 MAKE_PIN(PortB, Pin03)
    #define  B4 MAKE_PIN(PortB, Pin04)
    #define  B5 MAKE_PIN(PortB, Pin05)
    #define  B6 MAKE_PIN(PortB, Pin06)
    #define  B7 MAKE_PIN(PortB, Pin07)
    #define  B8 MAKE_PIN(PortB, Pin08)
    #define  B9 MAKE_PIN(PortB, Pin09)
    #define B10 MAKE_PIN(PortB, Pin10)
    #define B11 MAKE_PIN(PortB, Pin11)
    #define B12 MAKE_PIN(PortB, Pin12)
    #define B13 MAKE_PIN(PortB, Pin13)
    #define B14 MAKE_PIN(PortB, Pin14)
    #define B15 MAKE_PIN(PortB, Pin15)

    #define  C0 MAKE_PIN(PortC, Pin00)
    #define  C1 MAKE_PIN(PortC, Pin01)
    #define  C2 MAKE_PIN(PortC, Pin02)
    #define  C3 MAKE_PIN(PortC, Pin03)
    #define  C4 MAKE_PIN(PortC, Pin04)
    #define  C5 MAKE_PIN(PortC, Pin05)
    #define  C6 MAKE_PIN(PortC, Pin06)
    #define  C7 MAKE_PIN(PortC, Pin07)
    #define  C8 MAKE_PIN(PortC, Pin08)
    #define  C9 MAKE_PIN(PortC, Pin09)
    #define C10 MAKE_PIN(PortC, Pin10)
    #define C11 MAKE_PIN(PortC, Pin11)
    #define C12 MAKE_PIN(PortC, Pin12)
    #define C13 MAKE_PIN(PortC, Pin13)
    #define C14 MAKE_PIN(PortC, Pin14)
    #define C15 MAKE_PIN(PortC, Pin15)

    #define  D0 MAKE_PIN(PortD, Pin00)
    #define  D1 MAKE_PIN(PortD, Pin01)
    #define  D2 MAKE_PIN(PortD, Pin02)
    #define  D3 MAKE_PIN(PortD, Pin03)
    #define  D4 MAKE_PIN(PortD, Pin04)
    #define  D5 MAKE_PIN(PortD, Pin05)
    #define  D6 MAKE_PIN(PortD, Pin06)
    #define  D7 MAKE_PIN(PortD, Pin07)
    #define  D8 MAKE_PIN(PortD, Pin08)
    #define  D9 MAKE_PIN(PortD, Pin09)
    #define D10 MAKE_PIN(PortD, Pin10)
    #define D11 MAKE_PIN(PortD, Pin11)
    #define D12 MAKE_PIN(PortD, Pin12)
    #define D13 MAKE_PIN(PortD, Pin13)
    #define D14 MAKE_PIN(PortD, Pin14)
    #define D15 MAKE_PIN(PortD, Pin15)

    #define  E0 MAKE_PIN(PortE, Pin00)
    #define  E1 MAKE_PIN(PortE, Pin01)
    #define  E2 MAKE_PIN(PortE, Pin02)
    #define  E3 MAKE_PIN(PortE, Pin03)
    #define  E4 MAKE_PIN(PortE, Pin04)
    #define  E5 MAKE_PIN(PortE, Pin05)
    #define  E6 MAKE_PIN(PortE, Pin06)
    #define  E7 MAKE_PIN(PortE, Pin07)
    #define  E8 MAKE_PIN(PortE, Pin08)
    #define  E9 MAKE_PIN(PortE, Pin09)
    #define E10 MAKE_PIN(PortE, Pin10)
    #define E11 MAKE_PIN(PortE, Pin11)
    #define E12 MAKE_PIN(PortE, Pin12)
    #define E13 MAKE_PIN(PortE, Pin13)
    #define E14 MAKE_PIN(PortE, Pin14)
    #define E15 MAKE_PIN(PortE, Pin15)

    #define  H0 MAKE_PIN(PortH, Pin00)
    #define  H1 MAKE_PIN(PortH, Pin01)
    #define  H2 MAKE_PIN(PortH, Pin02)
    #define  H3 MAKE_PIN(PortH, Pin03)
    #define  H4 MAKE_PIN(PortH, Pin04)
    #define  H5 MAKE_PIN(PortH, Pin05)
    #define  H6 MAKE_PIN(PortH, Pin06)
    #define  H7 MAKE_PIN(PortH, Pin07)
    #define  H8 MAKE_PIN(PortH, Pin08)
    #define  H9 MAKE_PIN(PortH, Pin09)
    #define H10 MAKE_PIN(PortH, Pin10)
    #define H11 MAKE_PIN(PortH, Pin11)
    #define H12 MAKE_PIN(PortH, Pin12)
    #define H13 MAKE_PIN(PortH, Pin13)
    #define H14 MAKE_PIN(PortH, Pin14)
    #define H15 MAKE_PIN(PortH, Pin15)

#else
    #error "MCU_TYPE not defined"
#endif

int gpio_read_pin(pin_t pin);
void gpio_write_pin(pin_t pin, int value);

uint32_t gpio_read_port(port_t port);
void gpio_write_port(port_t port, uint32_t value);

void gpio_set_output_pushpull(pin_t pin);
void gpio_set_output_opendrain(pin_t pin);

void gpio_set_input_floating(pin_t pin);
void gpio_set_input_pullup(pin_t pin);
void gpio_set_input_pulldown(pin_t pin);
