PLATFORM_PORTING_DIR := $(MAIN_DIR)/porting/wired/gd32

SRCS += \
	$(PLATFORM_PORTING_DIR)/gpio_pin.c \
	$(PLATFORM_PORTING_DIR)/wait.c \
	$(PLATFORM_PORTING_DIR)/gd32.c \

INCS += \
	$(PLATFORM_PORTING_DIR) \

SRCS += $(PLATFORM_PORTING_DIR)/gd32_tinyusb.c
#SRCS += $(PLATFORM_PORTING_DIR)/gd32_usb.c
