PLATFORM_PORTING_DIR := $(MAIN_DIR)/porting/wired/hc32

SRCS += \
	$(PLATFORM_PORTING_DIR)/gpio_pin.c \
	$(PLATFORM_PORTING_DIR)/wait.c \
	$(PLATFORM_PORTING_DIR)/hc32.c \

INCS += \
	$(PLATFORM_PORTING_DIR) \
