
SRCS += $(KEYBOARD_DIR)/m65.c
APP_DEFS += -DPOWER_CHIP_PIN=A6

MCU = STM32F405

TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
SCREEN_ENABLE = yes
SCREEN_DRIVER = RM67160
MSC_ENABLE = yes
EECONFIG_FLASH = yes
RGB_LINEAR_ENABLE = yes
RGB_INDICATOR_ENABLE = yes
#DATETIME_ENABLE = yes
#VIAL_ENABLE = yes
#RTOS_ENABLE = yes
DYNAMIC_CONFIGURATION = yes
USE_F405_V2 = yes
UF2_ENABLE = yes
UF2_FAMILY = STM32F4

LINKER_PATH = $(KEYBOARD_DIR)

ifeq (yes, $(strip $(VIAL_ENABLE)))
	SRCS += $(KEYBOARD_DIR)/m65_actionmap.c
else
	SRCS += $(KEYBOARD_DIR)/m65_keymap.c
endif
