
MCU = STM32F405

TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
MSC_ENABLE = yes
EECONFIG_FLASH = yes
RGB_LINEAR_ENABLE = yes
RGB_INDICATOR_ENABLE = yes
DYNAMIC_CONFIGURATION = yes
USE_F405_V2 = yes
UF2_ENABLE = yes
UF2_FAMILY = STM32F4
VIAL_ENABLE = yes

LINKER_PATH = $(KEYBOARD_DIR)

ifeq (yes, $(strip $(VIAL_ENABLE)))
	SRCS += $(KEYBOARD_DIR)/m65_gcmap.c
else
	SRCS += $(KEYBOARD_DIR)/m65_keymap.c
endif

SRCS += $(KEYBOARD_DIR)/m65.c
SRCS += $(KEYBOARD_DIR)/display.c
SRCS += $(MAIN_DIR)/drivers/ssd1357.c
