/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v14.0
processor: LPC5516
package_id: LPC5516JBD64
mcu_data: ksdk2_0
processor_version: 15.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: f40f089a-30dc-498f-99b9-d9892ccb829e
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * MPU initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MPU'
- type: 'mpu_utility'
- mode: 'MPU'
- custom_name_enabled: 'false'
- type_id: 'mpu_utility_bc3ea1f6add76edb6050f698d423d163'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MPU'
- config_sets:
  - mpu_init:
    - mpuInit: 'disabled'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void MPU_init(void) {
} */

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO'
- type: 'lpc_gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'lpc_gpio_8c9ab9b3668a514c1f4609fe43001865'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO'
- config_sets:
  - lpc_gpio: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void GPIO_init(void) {
} */

/***********************************************************************************************************************
 * ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC0'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'false'
- type_id: 'lpadc_62bb06ef5585c73eb81e242721fa56b2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - clockSource: 'AsynchronousFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - enableInDozeMode: 'true'
      - conversionAverageMode: 'kLPADC_ConversionAverage1'
      - offsetCalibration: 'no'
      - autoCalibrate: 'false'
      - enableAnalogPreliminary: 'false'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt2'
      - powerLevelMode: 'kLPADC_PowerLevelAlt1'
      - triggerPriorityPolicy: 'kLPADC_ConvPreemptImmediatelyNotAutoResumed'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFO0Watermark: '0'
      - FIFO1Watermark: '0'
      - FIFO0WatermarkDMA: 'false'
      - FIFO1WatermarkDMA: 'false'
    - lpadcConvCommandConfig: []
    - lpadcConvTriggerConfig: []
    - IRQ_cfg:
      - interrupt_type: ''
      - enable_irq: 'false'
      - adc_interrupt:
        - IRQn: 'ADC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
    - quick_selection: 'QS_LPADC_1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t ADC0_config = {
  .enableInDozeMode = true,
  .conversionAverageMode = kLPADC_ConversionAverage1,
  .enableAnalogPreliminary = false,
  .powerUpDelay = 0x80UL,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt2,
  .powerLevelMode = kLPADC_PowerLevelAlt1,
  .triggerPriorityPolicy = kLPADC_ConvPreemptImmediatelyNotAutoResumed,
  .enableConvPause = false,
  .convPauseDelay = 0UL,
  .FIFO0Watermark = 0UL,
  .FIFO1Watermark = 0UL
};

static void ADC0_init(void) {
  /* Power up LDO for ADC */
  POWER_DisablePD(kPDRUNCFG_PD_LDOGPADC);
  /* Initialize LPADC converter */
  LPADC_Init(ADC0_PERIPHERAL, &ADC0_config);
}

/***********************************************************************************************************************
 * USBHSD initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USBHSD'
- type: 'usb'
- mode: 'device'
- custom_name_enabled: 'false'
- type_id: 'usb_cbf31fb9a3cef21890d93e737c3d2690'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'USBHSD'
- config_sets:
  - deviceSetting:
    - vendor_id: '0x1FC9'
    - product_id: '0x0090'
    - manufacturer_string: 'NXP'
    - product_string: 'Product'
    - self_powered: 'false'
    - max_power: '100'
    - interfaces:
      - 0:
        - interface_class: 'kClassHid'
        - setting_hid:
          - interface_name: 'HID Keyboard'
          - subclass: 'kSubclassBootInterface'
          - protocol: 'kProtocolKeyboard'
          - implementation: 'kImplementationKeyboard'
          - endpoints_settings:
            - 0:
              - setting_name: 'Default'
              - endpoints:
                - 0:
                  - direction: 'kIn'
                  - transfer_type: 'kInterrupt'
                  - synchronization: 'kNoSynchronization'
                  - usage: 'kData'
                  - max_packet_size_fs: 'k8'
                  - polling_interval_fs: '4'
                  - max_packet_size_hs: 'k8'
                  - polling_interval_hs: '6'
                  - bRefresh: '0'
                  - bSynchAddress: 'NoSynchronization'
          - report_descriptor:
            - 0:
              - type: 'kUsage_Page'
              - value: '0x01'
              - remarks: 'Usage Page (Generic Desktop)'
            - 1:
              - type: 'kUsage'
              - value: '0x06'
              - remarks: 'Usage (Keyboard)'
            - 2:
              - type: 'kCollection'
              - value: '0x01'
              - remarks: 'Collection (Application)'
            - 3:
              - type: 'kReport_Size'
              - value: '0x01'
              - remarks: 'Report Size (1U)'
            - 4:
              - type: 'kReport_Count'
              - value: '0x08'
              - remarks: 'Report Count (8U)'
            - 5:
              - type: 'kUsage_Page'
              - value: '0x07'
              - remarks: 'Usage Page(Key Codes)'
            - 6:
              - type: 'kUsage_Minimum'
              - value: '0xE0'
              - remarks: 'Usage Minimum (224U)'
            - 7:
              - type: 'kUsage_Maximum'
              - value: '0xE7'
              - remarks: 'Usage Maximum (231U)'
            - 8:
              - type: 'kLogical_Minimum'
              - value: '0x00'
              - remarks: 'Logical Minimum (0U)'
            - 9:
              - type: 'kLogical_Maximum'
              - value: '0x01'
              - remarks: 'Logical Maximum (1U)'
            - 10:
              - type: 'kInput'
              - value: '0x02'
              - remarks: 'Input(Data, Variable, Absolute) Modifier byte'
            - 11:
              - type: 'kReport_Count'
              - value: '0x01'
              - remarks: 'Report Count (1U)'
            - 12:
              - type: 'kReport_Size'
              - value: '0x08'
              - remarks: 'Report Size (8U)'
            - 13:
              - type: 'kInput'
              - value: '0x01'
              - remarks: 'Input(Constant), Reserved byte'
            - 14:
              - type: 'kReport_Count'
              - value: '0x05'
              - remarks: 'Report Count (5U)'
            - 15:
              - type: 'kReport_Size'
              - value: '0x01'
              - remarks: 'Report Size (1U)'
            - 16:
              - type: 'kUsage_Page'
              - value: '0x08'
              - remarks: 'Usage Page (Page# for LEDs)'
            - 17:
              - type: 'kUsage_Minimum'
              - value: '0x01'
              - remarks: 'Usage Minimum (1U)'
            - 18:
              - type: 'kUsage_Maximum'
              - value: '0x05'
              - remarks: 'Usage Maximum (5U)'
            - 19:
              - type: 'kOutput'
              - value: '0x02'
              - remarks: 'Output (Data, Variable, Absolute) LED report'
            - 20:
              - type: 'kReport_Count'
              - value: '0x01'
              - remarks: 'Report Count (1U)'
            - 21:
              - type: 'kReport_Size'
              - value: '0x03'
              - remarks: 'Report Size (3U)'
            - 22:
              - type: 'kOutput'
              - value: '0x03'
              - remarks: 'Output (Constant), LED report padding'
            - 23:
              - type: 'kReport_Count'
              - value: '0x06'
              - remarks: 'Report Count (6U)'
            - 24:
              - type: 'kReport_Size'
              - value: '0x08'
              - remarks: 'Report Size (8U)'
            - 25:
              - type: 'kLogical_Minimum'
              - value: '0x00'
              - remarks: 'Logical Minimum (0U)'
            - 26:
              - type: 'kLogical_Maximum'
              - value: '0xFF'
              - remarks: 'Logical Maximum (255U)'
            - 27:
              - type: 'kUsage_Page'
              - value: '0x07'
              - remarks: 'Usage Page (Key Codes)'
            - 28:
              - type: 'kUsage_Minimum'
              - value: '0x00'
              - remarks: 'Usage Minimum (0U)'
            - 29:
              - type: 'kUsage_Maximum'
              - value: '0xFF'
              - remarks: 'Usage Maximum (255U)'
            - 30:
              - type: 'kInput'
              - value: '0x00'
              - remarks: 'Input(Data, Array), Key arrays(6U bytes)'
            - 31:
              - type: 'kEnd_Collection'
              - remarks: ''
          - quick_selection: 'QS_INTERFACE_HID_KEYBOARD'
  - commonSettings:
    - mpu_init:
      - mpu_init_component: 'MPU'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void USBHSD_init(void) {
  USB_DeviceApplicationInit();
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  ARM_MPU_Disable();

  /* Initialize components */
  ADC0_init();
  USBHSD_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
