
MCU = STM32F411
TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
EECONFIG_FLASH = yes
RGB_LINEAR_ENABLE = yes
VIAL_ENABLE = yes
NKRO_AUTO_ENABLE = yes
AMK_CUSTOM_MATRIX = yes

LINKER_PATH = $(KEYBOARD_DIR)

UF2_ENABLE = yes
UF2_FAMILY = STM32F4

SRCS += $(KEYBOARD_DIR)/me_ec.c
SRCS += $(KEYBOARD_DIR)/ec_matrix.c