
MCU = STM32F411
TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
EECONFIG_FLASH = yes
MSC_ENABLE = yes
DYNAMIC_CONFIGURATION = yes
VIAL_ENABLE = yes
NKRO_ENABLE = yes
AMK_CUSTOM_MATRIX = yes
DEBOUNCE_TYPE = none

UF2_ENABLE = yes
UF2_FAMILY = STM32F4

LINKER_PATH = $(KEYBOARD_DIR)

SRCS += $(KEYBOARD_DIR)/corsa_ec.c
SRCS += $(KEYBOARD_DIR)/ec_matrix.c

SRCS += $(KEYBOARD_DIR)/display.c
SRCS += $(MAIN_DIR)/drivers/st7735.c
