LVGL_DIR := $(TOP_DIR)/lib/lvgl

SRC_FILES += \
		$(LVGL_DIR)/core/src/lv_core/lv_group.c \
		$(LVGL_DIR)/core/src/lv_core/lv_indev.c \
		$(LVGL_DIR)/core/src/lv_core/lv_disp.c \
		$(LVGL_DIR)/core/src/lv_core/lv_obj.c \
		$(LVGL_DIR)/core/src/lv_core/lv_refr.c \
		$(LVGL_DIR)/core/src/lv_core/lv_style.c \
		$(LVGL_DIR)/core/src/lv_hal/lv_hal_disp.c \
		$(LVGL_DIR)/core/src/lv_hal/lv_hal_indev.c \
		$(LVGL_DIR)/core/src/lv_hal/lv_hal_tick.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_arc.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_bar.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_checkbox.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_cpicker.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_dropdown.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_keyboard.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_line.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_msgbox.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_spinner.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_roller.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_table.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_tabview.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_tileview.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_btn.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_calendar.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_chart.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_canvas.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_gauge.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_label.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_list.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_slider.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_textarea.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_spinbox.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_btnmatrix.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_cont.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_img.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_imgbtn.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_led.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_linemeter.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_page.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_switch.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_win.c \
		$(LVGL_DIR)/core/src/lv_widgets/lv_objmask.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_fmt_txt.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_loader.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_12.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_14.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_16.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_18.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_20.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_22.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_24.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_26.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_28.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_30.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_32.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_34.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_36.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_38.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_40.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_42.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_44.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_46.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_48.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_12_subpx.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_montserrat_28_compressed.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_unscii_8.c \
		$(LVGL_DIR)/core/src/lv_font/lv_font_dejavu_16_persian_hebrew.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_area.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_task.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_fs.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_anim.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_mem.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_ll.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_color.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_txt.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_txt_ap.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_math.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_log.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_gc.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_utils.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_async.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_printf.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_bidi.c \
		$(LVGL_DIR)/core/src/lv_misc/lv_debug.c \
		$(LVGL_DIR)/core/src/lv_themes/lv_theme.c \
		$(LVGL_DIR)/core/src/lv_themes/lv_theme_material.c \
		$(LVGL_DIR)/core/src/lv_themes/lv_theme_mono.c \
		$(LVGL_DIR)/core/src/lv_themes/lv_theme_empty.c \
		$(LVGL_DIR)/core/src/lv_themes/lv_theme_template.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_mask.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_blend.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_rect.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_label.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_line.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_img.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_arc.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_draw_triangle.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_img_decoder.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_img_cache.c \
		$(LVGL_DIR)/core/src/lv_draw/lv_img_buf.c \
		$(LVGL_DIR)/core/src/lv_gpu/lv_gpu_stm32_dma2d.c \

INC_FOLDERS += \
		$(LVGL_DIR)/core \
		$(LVGL_DIR)/core/src/lv_core \
		$(LVGL_DIR)/core/src/lv_hal \
		$(LVGL_DIR)/core/src/lv_widgets \
		$(LVGL_DIR)/core/src/lv_font \
		$(LVGL_DIR)/core/src/lv_misc \
		$(LVGL_DIR)/core/src/lv_themes \
		$(LVGL_DIR)/core/src/lv_draw \
		$(LVGL_DIR)/core/src/lv_gpu \

APP_DEFS += \
		-DLV_CONF_INCLUDE_SIMPLE