/**
 * @file gpio_hc32.h
 * @author astro
 * 
 * @copyright Copyright (c) 2022
 * 
 */

#pragma once

    #include "generic_hal.h"

    #define INVALID_PIN 0xFFFFFFFF
    typedef uint32_t pin_t;
    typedef uint32_t port_t;

    #define MAKE_PIN(port, pin)     ((uint32_t) (((port)<<16)|((pin)&0xFFFF)))
    #define GET_PIN(port_pin)       ((port_pin)&0xFFFF)
    #define GET_PORT(port_pin)      (((port_pin)>>16)&0xFFFF)

    #define  A0 MAKE_PIN(PortA, Pin00)
    #define  A1 MAKE_PIN(PortA, Pin01)
    #define  A2 MAKE_PIN(PortA, Pin02)
    #define  A3 MAKE_PIN(PortA, Pin03)
    #define  A4 MAKE_PIN(PortA, Pin04)
    #define  A5 MAKE_PIN(PortA, Pin05)
    #define  A6 MAKE_PIN(PortA, Pin06)
    #define  A7 MAKE_PIN(PortA, Pin07)
    #define  A8 MAKE_PIN(PortA, Pin08)
    #define  A9 MAKE_PIN(PortA, Pin09)
    #define A10 MAKE_PIN(PortA, Pin10)
    #define A11 MAKE_PIN(PortA, Pin11)
    #define A12 MAKE_PIN(PortA, Pin12)
    #define A13 MAKE_PIN(PortA, Pin13)
    #define A14 MAKE_PIN(PortA, Pin14)
    #define A15 MAKE_PIN(PortA, Pin15)

    #define  B0 MAKE_PIN(PortB, Pin00)
    #define  B1 MAKE_PIN(PortB, Pin01)
    #define  B2 MAKE_PIN(PortB, Pin02)
    #define  B3 MAKE_PIN(PortB, Pin03)
    #define  B4 MAKE_PIN(PortB, Pin04)
    #define  B5 MAKE_PIN(PortB, Pin05)
    #define  B6 MAKE_PIN(PortB, Pin06)
    #define  B7 MAKE_PIN(PortB, Pin07)
    #define  B8 MAKE_PIN(PortB, Pin08)
    #define  B9 MAKE_PIN(PortB, Pin09)
    #define B10 MAKE_PIN(PortB, Pin10)
    #define B11 MAKE_PIN(PortB, Pin11)
    #define B12 MAKE_PIN(PortB, Pin12)
    #define B13 MAKE_PIN(PortB, Pin13)
    #define B14 MAKE_PIN(PortB, Pin14)
    #define B15 MAKE_PIN(PortB, Pin15)

    #define  C0 MAKE_PIN(PortC, Pin00)
    #define  C1 MAKE_PIN(PortC, Pin01)
    #define  C2 MAKE_PIN(PortC, Pin02)
    #define  C3 MAKE_PIN(PortC, Pin03)
    #define  C4 MAKE_PIN(PortC, Pin04)
    #define  C5 MAKE_PIN(PortC, Pin05)
    #define  C6 MAKE_PIN(PortC, Pin06)
    #define  C7 MAKE_PIN(PortC, Pin07)
    #define  C8 MAKE_PIN(PortC, Pin08)
    #define  C9 MAKE_PIN(PortC, Pin09)
    #define C10 MAKE_PIN(PortC, Pin10)
    #define C11 MAKE_PIN(PortC, Pin11)
    #define C12 MAKE_PIN(PortC, Pin12)
    #define C13 MAKE_PIN(PortC, Pin13)
    #define C14 MAKE_PIN(PortC, Pin14)
    #define C15 MAKE_PIN(PortC, Pin15)

    #define  D0 MAKE_PIN(PortD, Pin00)
    #define  D1 MAKE_PIN(PortD, Pin01)
    #define  D2 MAKE_PIN(PortD, Pin02)
    #define  D3 MAKE_PIN(PortD, Pin03)
    #define  D4 MAKE_PIN(PortD, Pin04)
    #define  D5 MAKE_PIN(PortD, Pin05)
    #define  D6 MAKE_PIN(PortD, Pin06)
    #define  D7 MAKE_PIN(PortD, Pin07)
    #define  D8 MAKE_PIN(PortD, Pin08)
    #define  D9 MAKE_PIN(PortD, Pin09)
    #define D10 MAKE_PIN(PortD, Pin10)
    #define D11 MAKE_PIN(PortD, Pin11)
    #define D12 MAKE_PIN(PortD, Pin12)
    #define D13 MAKE_PIN(PortD, Pin13)
    #define D14 MAKE_PIN(PortD, Pin14)
    #define D15 MAKE_PIN(PortD, Pin15)

    #define  E0 MAKE_PIN(PortE, Pin00)
    #define  E1 MAKE_PIN(PortE, Pin01)
    #define  E2 MAKE_PIN(PortE, Pin02)
    #define  E3 MAKE_PIN(PortE, Pin03)
    #define  E4 MAKE_PIN(PortE, Pin04)
    #define  E5 MAKE_PIN(PortE, Pin05)
    #define  E6 MAKE_PIN(PortE, Pin06)
    #define  E7 MAKE_PIN(PortE, Pin07)
    #define  E8 MAKE_PIN(PortE, Pin08)
    #define  E9 MAKE_PIN(PortE, Pin09)
    #define E10 MAKE_PIN(PortE, Pin10)
    #define E11 MAKE_PIN(PortE, Pin11)
    #define E12 MAKE_PIN(PortE, Pin12)
    #define E13 MAKE_PIN(PortE, Pin13)
    #define E14 MAKE_PIN(PortE, Pin14)
    #define E15 MAKE_PIN(PortE, Pin15)

    #define  H0 MAKE_PIN(PortH, Pin00)
    #define  H1 MAKE_PIN(PortH, Pin01)
    #define  H2 MAKE_PIN(PortH, Pin02)
    #define  H3 MAKE_PIN(PortH, Pin03)
    #define  H4 MAKE_PIN(PortH, Pin04)
    #define  H5 MAKE_PIN(PortH, Pin05)
    #define  H6 MAKE_PIN(PortH, Pin06)
    #define  H7 MAKE_PIN(PortH, Pin07)
    #define  H8 MAKE_PIN(PortH, Pin08)
    #define  H9 MAKE_PIN(PortH, Pin09)
    #define H10 MAKE_PIN(PortH, Pin10)
    #define H11 MAKE_PIN(PortH, Pin11)
    #define H12 MAKE_PIN(PortH, Pin12)
    #define H13 MAKE_PIN(PortH, Pin13)
    #define H14 MAKE_PIN(PortH, Pin14)
    #define H15 MAKE_PIN(PortH, Pin15)
