
MCU = STM32F405
TINYUSB_ENABLE = yes
USE_F405_APM = yes

EECONFIG_FLASH = yes
RGB_LINEAR_ENABLE = yes
VIAL_ENABLE = yes
NKRO_ENABLE = yes
AMK_CUSTOM_MATRIX = cms
DEBOUNCE_TYPE = none

MSC_ENABLE = yes
DYNAMIC_CONFIGURATION = yes


LINKER_PATH = $(KEYBOARD_DIR)

UF2_ENABLE = yes
UF2_FAMILY = STM32F4

SRCS += $(KEYBOARD_DIR)/ms_navi.c
#SRCS += $(KEYBOARD_DIR)/apc_matrix.c
#SRCS += $(KEYBOARD_DIR)/uart_cmd.c
SRCS += $(KEYBOARD_DIR)/display.c
SRCS += $(MAIN_DIR)/drivers/st7735.c

#NO_DEBUG := 1
#VIAL_JSON_NAME = vial_v1

#RTOS_ENABLE = yes
#ASMFLAGS += -DSYSTEM_CLOCK=168000000

