
MCU = STM32F405
USE_F405_APM = yes

TINYUSB_ENABLE = yes
#EECONFIG_FLASH = yes
MSC_ENABLE = yes
DYNAMIC_CONFIGURATION = yes
RGB_LINEAR_ENABLE = yes
VIAL_ENABLE = yes
NKRO_ENABLE = yes
PORT_SCAN_ENABLE = yes
STATE_SCAN_ENABLE = yes
DEBOUNCE_TYPE = none

LINKER_PATH = $(KEYBOARD_DIR)

UF2_ENABLE = yes
UF2_FAMILY = STM32F4

SRCS += $(KEYBOARD_DIR)/navi_8k.c

SRCS += $(KEYBOARD_DIR)/display.c
SRCS += $(MAIN_DIR)/drivers/st7735.c
